# Generated by Django 4.2.15 on 2025-07-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dsc', models.CharField(max_length=350)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ProductCategoryImage')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=112)),
                ('dsc', models.CharField(max_length=550)),
                ('image', models.ImageField(upload_to='product_images')),
            ],
        ),
    ]
