# Generated by Django 4.2.15 on 2025-07-13 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=3240, on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
